Repository lypitech/area, pull requests merged in 2025-09, with the labels that each got.

#6 Benchmark document
  benchmark/DEV-500 ‒ Area ‒ Stack Benchmark.pdf
  benchmark/benchmark.md
Labels: documentation

#16 Add PoC to frontend
  frontend/web/.gitignore
  frontend/web/README.md
  frontend/web/eslint.config.js
  frontend/web/index.html
  frontend/web/package.json
  frontend/web/src/assets/fonts/Kanit/Kanit-Regular.ttf
  frontend/web/src/assets/fonts/Kanit/OFL.txt
  frontend/web/src/assets/logo.png
  frontend/web/src/assets/svg/admin.svg
  frontend/web/src/assets/svg/at.svg
  frontend/web/src/assets/svg/catalog.svg
  frontend/web/src/assets/svg/dashboard.svg
  frontend/web/src/assets/svg/events.svg
  frontend/web/src/assets/svg/home.svg
  frontend/web/src/assets/svg/lock.svg
  frontend/web/src/assets/svg/login.svg
  frontend/web/src/assets/svg/logout.svg
  frontend/web/src/assets/svg/mail.svg
  frontend/web/src/assets/svg/news.svg
  frontend/web/src/assets/svg/page.svg
  frontend/web/src/assets/svg/pen.svg
  frontend/web/src/assets/svg/return.svg
  frontend/web/src/assets/svg/search.svg
  frontend/web/src/components/Button.tsx
  frontend/web/src/components/Input.tsx
  frontend/web/src/components/Loader.tsx
  frontend/web/src/components/LoadingLogin.tsx
  frontend/web/src/components/icons/admin.tsx
  frontend/web/src/components/icons/at.tsx
  frontend/web/src/components/icons/catalog.tsx
  frontend/web/src/components/icons/dashboard.tsx
  frontend/web/src/components/icons/events.tsx
  frontend/web/src/components/icons/home.tsx
  frontend/web/src/components/icons/icons.tsx
  frontend/web/src/components/icons/lock.tsx
  frontend/web/src/components/icons/login.tsx
  frontend/web/src/components/icons/logout.tsx
  frontend/web/src/components/icons/mail.tsx
  frontend/web/src/components/icons/news.tsx
  frontend/web/src/components/icons/page.tsx
  frontend/web/src/components/icons/pen.tsx
  frontend/web/src/components/icons/return.tsx
  frontend/web/src/components/icons/search.tsx
  frontend/web/src/index.css
  frontend/web/src/main.tsx
  frontend/web/src/pages/Home.tsx
  frontend/web/src/pages/Login.tsx
  frontend/web/src/pages/Register.tsx
  frontend/web/src/pages/Workflows.tsx
  frontend/web/src/router.tsx
  frontend/web/src/vite-env.d.ts
  frontend/web/tsconfig.app.json
  frontend/web/tsconfig.json
  frontend/web/tsconfig.node.json
  frontend/web/vite.config.ts
Labels: enhancement

#8 mobile: PoC
  frontend/mobile/.env.sample
  frontend/mobile/assets/font/Kanit-Black.ttf
  frontend/mobile/assets/font/Kanit-BlackItalic.ttf
  frontend/mobile/assets/font/Kanit-Bold.ttf
  frontend/mobile/assets/font/Kanit-BoldItalic.ttf
  frontend/mobile/assets/font/Kanit-ExtraBold.ttf
  frontend/mobile/assets/font/Kanit-ExtraBoldItalic.ttf
  frontend/mobile/assets/font/Kanit-ExtraLight.ttf
  frontend/mobile/assets/font/Kanit-ExtraLightItalic.ttf
  frontend/mobile/assets/font/Kanit-Italic.ttf
  frontend/mobile/assets/font/Kanit-Light.ttf
  frontend/mobile/assets/font/Kanit-LightItalic.ttf
  frontend/mobile/assets/font/Kanit-Medium.ttf
  frontend/mobile/assets/font/Kanit-MediumItalic.ttf
  frontend/mobile/assets/font/Kanit-Regular.ttf
  frontend/mobile/assets/font/Kanit-SemiBold.ttf
  frontend/mobile/assets/font/Kanit-SemiBoldItalic.ttf
  frontend/mobile/assets/font/Kanit-Thin.ttf
  frontend/mobile/assets/font/Kanit-ThinItalic.ttf
  frontend/mobile/lib/api/auth_api.dart
  frontend/mobile/lib/app.dart
  frontend/mobile/lib/core/constant/constants.dart
  frontend/mobile/lib/core/router.dart
  frontend/mobile/lib/core/theme/theme.dart
  frontend/mobile/lib/data/provider/auth_api_provider.dart
  frontend/mobile/lib/data/provider/auth_service_provider.dart
  frontend/mobile/lib/data/provider/auth_state_provider.dart
  frontend/mobile/lib/data/provider/dio_provider.dart
  frontend/mobile/lib/feature/presentation/main_page.dart
  frontend/mobile/lib/l10n/app_en.arb
  frontend/mobile/lib/l10n/app_fr.arb
  frontend/mobile/lib/presentation/auth/login_page.dart
  frontend/mobile/lib/presentation/error_page.dart
  frontend/mobile/lib/presentation/main_page.dart
  frontend/mobile/lib/service/auth_service.dart
  frontend/mobile/lib/widget/a_text_field.dart
  frontend/mobile/lib/widget/clickable_frame.dart
  frontend/mobile/lib/widget/dot_stepper.dart
  frontend/mobile/lib/widget/logo.dart
  frontend/mobile/pubspec.lock
  frontend/mobile/pubspec.yaml
Labels: enhancement

#20 Frontend: hotfix
  frontend/web/src/pages/Login.tsx
Labels: bug
